<?xml version="1.0"?>
<!-- Revolute-Revolute Manipulator -->
<robot name="rrbot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Constants for robot dimensions -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="mass" value="1" /> <!-- arbitrary value for mass -->
  <xacro:property name="width" value="0.075" /> <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="boxwidth" value="1" /> <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="boxheight" value="0.1" /> <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="width3" value="0.1" /> <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="d1" value="0.47625" /> <!-- Distance from ground to second joint -->
  <xacro:property name="a1" value="0.05398" /> <!-- Horizontal offset from turret to first joint -->
  <xacro:property name="a2" value="0.3857625" /> <!-- First tube length -->
  <xacro:property name="a3" value="0.06985" /> <!-- Vertical offset to next link-->
  <xacro:property name="d4" value="0.358775" /> <!-- 2nd tube length -->
  <xacro:property name="d6" value="0.238125" /> <!-- Distance from dynamixel joint to claw tip -->
  <xacro:property name="dyn" value="0" /> <!-- Dynamixel length -->
  <xacro:property name="axel_offset" value="0.05" /> <!-- Space btw top of beam and the each joint -->

  <!-- Import all Gazebo-customization elements, including Gazebo colors -->
  <xacro:include filename="$(find rover_description)/urdf/hal.gazebo" />
  <!-- Import Rviz colors -->
  <xacro:include filename="$(find rover_description)/urdf/materials.xacro" />

  <!-- Used for fixing robot to Gazebo 'base_link' -->
  <link name="world"/>

  <joint name="fixed" type="fixed">
    <parent link="world"/>
    <child link="link1"/>
  </joint>

  <!-- Base Link -->
  <link name="link1">
    <!--collision>
      <origin xyz="0 0 ${length1/2}" rpy="0 0 0"/>
      <geometry>
  <box size="${width} ${width} ${length1}"/>
      </geometry>
    </collision-->

    <visual>
      <origin xyz="0 0 ${-boxheight/2 + d1}" rpy="0 0 0"/>
      <geometry>
  <box size="${boxwidth} ${boxwidth} ${boxheight}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${-boxheight/2 + d1}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
    ixx="${mass / 12.0 * (boxwidth*boxwidth + boxheight*boxheight)}" ixy="0.0" ixz="0.0"
    iyy="${mass / 12.0 * (boxheight*boxheight + boxwidth*boxwidth)}" iyz="0.0"
    izz="${mass / 12.0 * (boxwidth*boxwidth + boxheight*boxheight)}"/>
    </inertial>
  </link>

  <!-- Turret-->
  <joint name="joint1" type="continuous"> 
    <parent link="link1"/>
    <child link="link2"/>
    <origin xyz="0 0 ${d1}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="0.7"/>
  </joint>

  <!-- Turret Box -->
  <link name="link2">
    <collision>
      <origin xyz="0 ${-a1/2} 0" rpy="0 0 0"/>
      <geometry>
  <box size="${width} ${a1} ${width}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 ${-a1/2} 0" rpy="0 0 0"/>
      <geometry>
  <box size="${width} ${a1} ${width}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="0 ${-a1/2} 0" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
    izz="${mass / 12.0 * (width*width + a1*a1)}" ixy="0.0" ixz="0.0"
    ixx="${mass / 12.0 * (a1*a1 + width*width)}" iyz="0.0"
    iyy="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>
  </link>

  <!-- Turret up/down -->
  <joint name="joint2" type="continuous">
    <parent link="link2"/>
    <child link="link3"/>
    <origin xyz="0 ${-a1} 0" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <dynamics damping="0.7"/>
  </joint>

  <!-- Tube 1  -->
  <link name="link3">
    <collision>
      <origin xyz="0 0 ${a2/2}" rpy="0 0 0"/>
      <geometry>
  <box size="${width} ${width} ${a2}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${a2/2}" rpy="0 0 0"/>
      <geometry>
  <box size="${width} ${width} ${a2}"/>
      </geometry>
      <material name="white"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${a2/2}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
    ixx="${mass / 12.0 * (width*width + a2*a2)}" ixy="0.0" ixz="0.0"
    iyy="${mass / 12.0 * (a2*a2 + width*width)}" iyz="0.0"
    izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>
  </link>
  
  <joint name="joint3" type="continuous">
    <parent link="link3"/>
    <child link="link4"/>
    <origin xyz="0 0 ${a2}" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <dynamics damping="0.7"/>
  </joint>

<!-- Offset Length -->
  <link name="link4">
    <collision>
      <origin xyz="0 0 ${a3/2}" rpy="0 0 0"/>
      <geometry>
  <box size="${width} ${width} ${a3}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${a3/2}" rpy="0 0 0"/>
      <geometry>
  <box size="${width} ${width} ${a3}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${a3/2}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
    ixx="${mass / 12.0 * (a3*a3 + a3*a3)}" ixy="0.0" ixz="0.0"
    iyy="${mass / 12.0 * (a3*a3 + width*width)}" iyz="0.0"
    izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>
  </link>
  
  <joint name="joint4" type="continuous">
    <parent link="link4"/>
    <child link="link5"/>
    <origin xyz="0 0 ${a3}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/>
  </joint>

  <!-- Second Arm -->
  <link name="link5">
    <collision>
      <origin xyz="0 ${-d4/2} 0" rpy="0 0 0"/>
      <geometry>
  <box size="${width} ${d4} ${width}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 ${-d4/2} 0" rpy="0 0 0"/>
      <geometry>
  <box size="${width} ${d4} ${width}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 ${-d4/2} 0" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
    izz="${mass / 12.0 * (width*width + d4*d4)}" ixy="0.0" ixz="0.0"
    ixx="${mass / 12.0 * (d4*d4 + width*width)}" iyz="0.0"
    iyy="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>
  </link>  
  
  <joint name="joint5" type="continuous">
    <parent link="link5"/>
    <child link="link6"/>
    <origin xyz="0 ${-d4} 0" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <dynamics damping="0.7"/>
  </joint>
  
   <!-- Zero-Length Link -->
  <link name="link6">
    <collision>
      <origin xyz="0 ${-dyn/2} 0" rpy="0 0 0"/>
      <geometry>
  <box size="${width} ${dyn} ${width}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 ${-dyn/2} 0" rpy="0 0 0"/>
      <geometry>
  <box size="${width} ${dyn} ${width}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="0 ${-dyn/2} 0" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
    izz="${mass / 12.0 * (width*width + dyn*dyn)}" ixy="0.0" ixz="0.0"
    ixx="${mass / 12.0 * (dyn*dyn + width*width)}" iyz="0.0"
    iyy="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>
  </link>  
  
  <joint name="joint6" type="continuous">
    <parent link="link6"/>
    <child link="link7"/>
    <origin xyz="0 ${-dyn} 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/>
  </joint>


   <!-- To Claw Tip -->
  <link name="link7">
    <collision>
      <origin xyz="0 ${-(d6-dyn)/2} 0" rpy="0 0 0"/>
      <geometry>
        <box size="${width} ${d6-dyn} ${width}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 ${-(d6-dyn)/2} 0" rpy="0 0 0"/>
      <geometry>
        <box size="${width} ${d6-dyn} ${width}"/>
      </geometry>
      <material name="white"/>
    </visual>

    <inertial>
      <origin xyz="0 ${-(d6-dyn)/2} 0" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
    izz="${mass / 12.0 * (width*width + (d6-dyn)*(d6-dyn))}" ixy="0.0" ixz="0.0"
    iyy="${mass / 12.0 * ((d6-dyn)*(d6-dyn) + width*width)}" iyz="0.0"
    ixx="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>
  </link>
  
  <joint name="joint7" type="fixed">
    <parent link="link7"/>
    <child link="end"/>
    <origin xyz="0 ${-(d6-dyn)} 0" rpy="0 0 0"/>
  </joint>
  
  <!-- Dummy Link to force KDL chain point to tip of claw -->
  <link name="end">
    <visual>
      <geometry>
        <box size="0 0 0"/>
      </geometry>
    </visual>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0"/>
      <inertia
        ixx="0" ixy="0" ixz="0"
        iyy="0" iyz="0"
        izz="0"
      />
    </inertial>
  </link>
      
      
</robot>
