<?xml version="1.0"?>
<!-- Revolute-Revolute Manipulator -->
<robot name="537_base" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Constants for robot dimensions -->
  <xacro:property name="PI" value="3.1415926535897931"/>

    <!-- collision box for flat top of rover  -->
  <xacro:property name="flattopwidth" value=".6096" />
  <xacro:property name="flattoplength" value=".8636" /> 
  <xacro:property name="flattopheight" value="0.0254" />
  <xacro:property name="flattop_offground" value="0.37465" />

    <!-- collision box for Power Box of rover  -->
  <xacro:property name="boxwidth" value="0.25" />
  <xacro:property name="boxlength" value="0.5" /> 
  <xacro:property name="boxheight" value="0.25" />

    <!-- collision box for Back Frok of rover  -->
  <xacro:property name="bforkwidth" value="0.1" />
  <xacro:property name="bforklength" value="0.75" /> 
  <xacro:property name="bforkheight" value="0.1" />

  <!-- Import all Gazebo-customization elements, including Gazebo colors -->
  <xacro:include filename="$(find hal_description)/urdf/hal.gazebo" />
  <!-- Import Rviz colors -->
  <xacro:include filename="$(find hal_description)/urdf/materials.xacro" />

  <!-- Used for fixing robot to Gazebo 'base_link' -->

  <link name="base_link"/>

  <joint name="fixed" type="fixed">
    <parent link="base_link"/>
    <child link="base1"/>
  </joint>

  <!-- Base Link -->
  <link name="base1">

    <visual>
      <origin xyz="0 0 ${flattop_offground + (1/2)*flattopheight}" rpy="0 0 0"/>
        <geometry>
	       <box size="${flattoplength} ${flattopwidth} ${flattopheight}"/>
        </geometry>
      <material name="white"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${flattop_offground + (1/2)*flattopheight}" rpy="0 0 0"/>
        <geometry>
	       <box size="${flattoplength} ${flattopwidth} ${flattopheight}"/>
        </geometry>
      <material name="white"/>
    </collision>

  </link>

   <joint name="topplate_to_box" type="fixed">
    <parent link="base1"/>
    <child link="box1"/>
    <origin xyz="${0.5*flattoplength} 0 ${flattop_offground + flattopheight}"/>
  </joint>

    <!-- Box Link -->
  <link name="box1">

    <visual>
      <origin xyz="${-0.5*boxwidth} 0 ${(1/2)*boxheight}" rpy="0 0 0"/>
        <geometry>
         <box size="${boxwidth} ${boxlength} ${boxheight}"/>
        </geometry>
      <material name="white"/>
    </visual>
    <collision>
      <origin xyz="${-0.5*boxwidth} 0 ${(1/2)*boxheight}" rpy="0 0 0"/>
        <geometry>
         <box size="${boxwidth} ${boxlength} ${boxheight}"/>
        </geometry>
      <material name="white"/>
    </collision>

  </link>

<!-- Joint from top plate to back fork -->
   <joint name="topplate_to_frontfork1" type="fixed">
    <parent link="base1"/>
    <child link="fork1"/>
    <origin xyz="${-0.5*flattoplength} 0 ${flattop_offground + flattopheight}"/>
  </joint>

    <!-- Back Fork Link -->
  <link name="fork1">

    <visual>
      <origin xyz="${-bforkwidth/2} ${0.5*bforklength} ${-0.771*bforklength/2}" rpy="${-45*PI/180} 0 0"/>
        <geometry>
         <box size="${bforkwidth} ${bforklength} ${bforkheight}"/>
        </geometry>
      <material name="white"/>
    </visual>
    <collision>
      <origin xyz="${-bforkwidth/2} ${0.5*bforklength} ${-0.771*bforklength/2}" rpy="${-45*PI/180} 0 0"/>
        <geometry>
         <box size="${bforkwidth} ${bforklength} ${bforkheight}"/>
        </geometry>
      <material name="white"/>
    </collision>
  </link>  

<!-- Joint from top plate to back fork -->
   <joint name="topplate_to_frontfork2" type="fixed">
    <parent link="base1"/>
    <child link="fork2"/>
    <origin xyz="${-0.5*flattoplength} 0 ${flattop_offground + flattopheight}"/>
  </joint>

<!-- Back Fork Link -->
  <link name="fork2">

    <visual>
      <origin xyz="${-bforkwidth/2} ${-0.5*bforklength} ${-0.771*bforklength/2}" rpy="${45*PI/180} 0 0"/>
        <geometry>
         <box size="${bforkwidth} ${bforklength} ${bforkheight}"/>
        </geometry>
      <material name="white"/>
    </visual>
    <collision>
      <origin xyz="${-bforkwidth/2} ${-0.5*bforklength} ${-0.771*bforklength/2}" rpy="${45*PI/180} 0 0"/>
        <geometry>
         <box size="${bforkwidth} ${bforklength} ${bforkheight}"/>
        </geometry>
      <material name="white"/>
    </collision>

  </link>

<!-- Joint from top plate to right front fork -->
<!--    <joint name="topplate_to_rightfrontfork1" type="fixed">
    <parent link="base1"/>
    <child link="rffork1"/>
    <origin xyz="0 0 ${flattop_offground + flattopheight}"/>
  </joint>
 -->
<!-- Back Fork Link -->
<!--   <link name="rffork1">

    <visual>
      <origin xyz="${-bforkwidth/2} ${-0.5*bforklength} ${-0.771*bforklength/2}" rpy="${45*PI/180} 0 0"/>
        <geometry>
         <box size="${bforkwidth} ${bforklength} ${bforkheight}"/>
        </geometry>
      <material name="white"/>
    </visual>

  </link>   --> 


  <!-- Turret-->
<!--   <joint name="joint1" type="continuous"> 
    <parent link="link1"/>
    <child link="link2"/>
    <origin xyz="0 0 ${d1}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="0.7"/>
  </joint> -->

  <!-- Turret Box -->
  <!-- <link name="link2">
    <collision>
      <origin xyz="0 ${-a1/2} 0" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${a1} ${width}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 ${-a1/2} 0" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${a1} ${width}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="0 ${-a1/2} 0" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
	  izz="${mass / 12.0 * (width*width + a1*a1)}" ixy="0.0" ixz="0.0"
	  ixx="${mass / 12.0 * (a1*a1 + width*width)}" iyz="0.0"
	  iyy="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>
  </link> -->

			
</robot>
