<?xml version="1.0"?>
<!-- Revolute-Revolute Manipulator -->
<robot name="rrbot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Constants for robot dimensions -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="mass" value="1" /> <!-- arbitrary value for mass -->
  <xacro:property name="width" value="0.075" /> <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="boxwidth" value="1" /> <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="boxheight" value="0.1" /> <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="width3" value="0.1" /> <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="d1" value="0.47625" /> <!-- Distance from ground to second joint -->
  <xacro:property name="a1" value="0.05398" /> <!-- Horizontal offset from turret to first joint -->
  <xacro:property name="a2" value="0.3857625" /> <!-- First tube length -->
  <xacro:property name="a3" value="0.06985" /> <!-- Vertical offset to next link-->
  <xacro:property name="d4" value="0.358775" /> <!-- 2nd tube length -->
  <xacro:property name="d6" value="0.238125" /> <!-- Distance from dynamixel joint to claw tip -->
  <xacro:property name="dyn" value="0" /> <!-- Dynamixel length -->
  <xacro:property name="axel_offset" value="0.05" /> <!-- Space btw top of beam and the each joint -->
  <xacro:property name="Torque" value = "40" />
  <xacro:property name="vel" value = "10" />

    <!-- collision box for flat top of rover  -->
  <xacro:property name="flattopwidth" value=".6096" />
  <xacro:property name="flattoplength" value=".8636" /> 
  <xacro:property name="flattopheight" value="0.0254" />
  <xacro:property name="flattop_offground" value="0.37465" />

  <!-- Import all Gazebo-customization elements, including Gazebo colors -->
  <xacro:include filename="$(find hal_description)/urdf/hal.gazebo" />
  <!-- Import Rviz colors -->
  <xacro:include filename="$(find hal_description)/urdf/materials.xacro" />

  <!-- Used for fixing robot to Gazebo 'base_link' -->
  <link name="world"/>

  <joint name="fixed" type="fixed">
    <parent link="world"/>
    <child link="base1"/>
  </joint>




  <!-- Base Link -->
  <link name="base1">
    <!--collision>
      <origin xyz="0 0 ${length1/2}" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${width} ${length1}"/>
      </geometry>
    </collision-->

    <visual>
      <origin xyz="0 0 ${flattop_offground + (1/2)*flattopheight}" rpy="0 0 0"/>
      <geometry>
	<box size="${flattoplength} ${flattopwidth} ${flattopheight}"/>
      </geometry>
      <material name="white"/>
    </visual>

    <!-- <inertial>
      <origin xyz="0 0 ${-boxheight/2 + d1}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (boxwidth*boxwidth + boxheight*boxheight)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (boxheight*boxheight + boxwidth*boxwidth)}" iyz="0.0"
	  izz="${mass / 12.0 * (boxwidth*boxwidth + boxheight*boxheight)}"/>
    </inertial> -->
  </link>

  <!-- Turret-->
<!--   <joint name="joint1" type="continuous"> 
    <parent link="link1"/>
    <child link="link2"/>
    <origin xyz="0 0 ${d1}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="0.7"/>
  </joint> -->

  <!-- Turret Box -->
  <!-- <link name="link2">
    <collision>
      <origin xyz="0 ${-a1/2} 0" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${a1} ${width}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 ${-a1/2} 0" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${a1} ${width}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="0 ${-a1/2} 0" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
	  izz="${mass / 12.0 * (width*width + a1*a1)}" ixy="0.0" ixz="0.0"
	  ixx="${mass / 12.0 * (a1*a1 + width*width)}" iyz="0.0"
	  iyy="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>
  </link> -->

			
</robot>
